version: '3.5'
services:
  web-server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - public
  
  database:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./src/database:/opt/global_chat/sql
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
